name: CI (playwright)

# Kích hoạt workflow khi có push hoặc pull request vào nhánh main
on:
    push:
        branches:
          - main
    pull_request:
        branches:
          - main
    workflow_dispatch:
jobs:
    test:
        # Sử dụng môi trường ubuntu-latest để chạy test
        runs-on: ubuntu-latest
        timeout-minutes: 30 
        # Giới hạn thời gian chạy job là 30 phút
        steps:
            # B1: lấy code tử repository
            - name: Pull code from repository (checkout)
              uses: actions/checkout@v2
            # B2: Cài đặt Node.js (phiên bản 20.0.0 hoặc mới hơn)
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: npm
            #B3: cài đặt các dependencies (library) của dự án
            - name: Install dependencies
              run: npm install
            #B4 tải browser (chromium) để chạy test
            - name: Install Playwright browsers
              run: npx playwright install --with-deps chromium

            #B4.1: Tạo file .env để lưu thoogn tin đăng nhập 
            - name: Create .env file
              run: |
                echo "USERNAME=${{secrets.USERNAME}}" >> .env
                echo "PASSWORD=${{secrets.PASSWORD}}" >> .env

            #B5 chạy test bằng Playwright
            - name: Run Playwright tests
              run: npx playwright test --project=chromium
            
            #B6: Tạo báo cáo test bằng allure
            - name: Generate Allure report
              if: always() # Đảm bảo bước này luôn được thực hiện dù test có thất bại hay không
              run: |
                # Kiểm tra nếu thư mục allure-results tồn tại, nếu không thì tạo mới
                if [ ! -d "allure-results" ]; then
                  #Nếu có thì tạo báo cáo allure
                  npm run -s allure:generate || true # bỏ qua lỗi nếu có và tiếp tục tạo báo cáo
                else
                  echo "Directory allure-results already exists. Skipping report generation."
                fi
                
            #B7: Upload báo cáo allure lên GitHub Actions
            - name: Upload Allure report
              if: always() # Đảm bảo bước này luôn được thực hiện dù test có thất bại hay không
              uses: actions/upload-artifact@v4
              with:
                name: playwright-allure-report
                if-no-files-found: warn
                #Liệt kê tất cả file cần upload
                path: |
                  playwright-report/
                  allure-results/
                  allure-report/
                  test-results/
            #B8: gửi báo cáo report quá slack

